### PR TITLE
fix: Return proper deployment DNS for Deployable Service

### LINKED ISSUE #3535: Fix Access the Deployable Service redirection
Scope:
- Currently, when deployment is successful and you click on "Access the deployment", there is a broken redirection. Fetch the proper deployment link from the IM API

### PR DESCRIPTION
**Pull request by wujuu**
closes #3535

### CODE REVIEW

File: app/jobs/deployable_service/deployment_job.rb [hunk 1]
```diff
@@ -43,7 +43,23 @@ def deploy_to_infrastructure_manager(_project_item, filled_template)
...
 
     if result[:success]
-      extract_deployment_uri(result[:data])
+      deployment_uri = extract_deployment_uri(result[:data])
+      return nil unless deployment_uri
+
+      # Extract infrastructure ID from URI and get outputs
+      infrastructure_id = extract_infrastructure_id(deployment_uri)
+      if infrastructure_id
+        outputs_result = im_client.get_outputs(infrastructure_id)
```
Comment (goreck888) [inline app/jobs/deployable_service/deployment_job.rb]: What do you think about initialization of the output_result and other incoming JSONs as a HashWithIndeferrentAccess? Then you don't need alternatives like that one:
```
outputs = outputs_result[:data]["outputs"] || outputs_result[:data][:outputs]
```
