### PR TITLE
[#2525] Show manage button on Resource and Provider views

### LINKED ISSUE #2525: Resource, Provider with MP upstream shouldn't have "Manage the resource", "Manage the Provider" button
Tested
v3.30.0-beta.1

**Describe the bug**
Resource, Provider with MP upstream shouldn't have "Manage the resource", "Manage the Provider" button which redirects to PC

image
image
image

### PR DESCRIPTION
**Pull request by kmarszalek**
Show button 'Manage the..' o Resource and Provider views only when
upstream is set to 'eosc_registry'

Fixes #2525

### CODE REVIEW

File: app/helpers/backoffice/services_helper.rb [hunk 1]
```diff
@@ -36,4 +36,8 @@ def preview_link_parameters(is_preview)
       {}
     end
   end
+
+  def show_manage_button?(service)
+    policy(service).data_administrator? && service.upstream&.eosc_registry?
+  end
```
Comment (goreck888) [inline app/helpers/backoffice/services_helper.rb:42]: Maybe use only one `show_manage_button?` method? The code is identical.

File: app/helpers/provider_helper.rb [hunk 2]
```diff
@@ -29,4 +29,8 @@ def field_tree(service, field)
     parents = service.send(field).map { |f| f.parent.blank? ? f : f.parent }
     parents.map { |parent| [parent.name, (parent.children & service.send(field)).map(&:name)] }.to_h
   end
+
+  def show_manage_button?(provider)
+    policy(provider).data_administrator? && provider.upstream&.eosc_registry?
```
Comment (goreck888) [inline app/helpers/provider_helper.rb:34]: as above

**Review by goreck888 — APPROVED** [review]
Generally code looks ok, consider removeing duplicated method.

File: app/helpers/backoffice/services_helper.rb (hunk 1 above)
Comment (kmarszalek) [reply app/helpers/backoffice/services_helper.rb]: done

File: app/helpers/provider_helper.rb (hunk 2 above)
Comment (kmarszalek) [reply app/helpers/provider_helper.rb]: done

**Comment by Marcelinna** [comment]
If we change upstream to MP we should lost access to ordering_configuration#offers page ??

image
image

**Review by Marcelinna — APPROVED** [review]
