### PR TITLE
[#2452] Fix redirect to PC

### LINKED ISSUE #2452: Fix redirect from MP to Resource dashboard in PC
**Describe the bug**
redirection to the Resource dashboard on PC was changed.

The current path should be ` https://providers.eosc-portal.eu/dashboard/#{resource_organisation_pid(service)}/resource-dashboard/#{service.pid}/stats`

e.g :  https://providers.eosc-portal.eu/dashboard/openaire/resource-dashboard/openaire.graph/stats

image

### PR DESCRIPTION
**Pull request by kmarszalek**
Closes #2452

### CODE REVIEW

**Review by Marcelinna — APPROVED** [review]

File: app/helpers/service/header_helper.rb [hunk 1]
```diff
@@ -12,9 +12,9 @@ def provider_header_fields
   def resource_link(service)
     if service.pid.present?
       "#{Mp::Application.config
-                        .providers_dashboard_url}/resource-dashboard/#{service.pid
-                                                                              .split(".")
-                                                                              .first}/#{service.pid}/stats"
+                        .providers_dashboard_url}/resource/#{service.pid
+                                                                    .split(".")
+                                                                    .first}/resource-dashboard/#{service.pid}/stats"
```
Comment (jswk) [inline app/helpers/service/header_helper.rb:17]: The resulting url, for example `https://beta.providers.eosc-portal.eu/resource/cyfronet/resource-dashboard/cyfronet.001_test_jms/stats` goes to 404.

The correct one is: `https://beta.providers.eosc-portal.eu/dashboard/cyfronet/resource-dashboard/cyfronet.001_test_jms/stats`.

File: app/helpers/service/header_helper.rb [hunk 2]
```diff
@@ -11,10 +11,8 @@ def provider_header_fields
 
   def resource_link(service)
     if service.pid.present?
-      "#{Mp::Application.config
-                        .providers_dashboard_url}/resource-dashboard/#{service.pid
-                                                                              .split(".")
-                                                                              .first}/#{service.pid}/stats"
+      "#{Mp::Application.config.providers_dashboard_url}/dashboard/" +
+      "#{service.resource_organisation_pid(service)}/resource-dashboard/#{service.pid}/stats"
```
Comment (jswk) [inline app/helpers/service/header_helper.rb:15]: `service.resource_organisation_pid(service)`?

**Review by jswk — APPROVED** [review]
