### PR TITLE
[#2387] Fix duplicating a project

### LINKED ISSUE #2387: Scientific domains are not duplicated when duplicating a project
Tested v3.24.0-beta.0"

**Describe the bug**
When the project is duplicated, the Scientific domain field is not duplicated

**To Reproduce**
1. Go to '/projects/new'
2. Fill all fields in creating project form
3. Click the button "Create new project"
4. Select the newly created project and click the button "Duplicate"
5. See error - Scientific Domain field is empty, isn't duplicated

**Expected behavior**
The scientific Domain field is duplicated

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by goreck888**
Fix copying scientific_domains
by duplicating a Project
Fixes #2387

### CODE REVIEW

File: app/controllers/projects_controller.rb [hunk 1]
```diff
@@ -73,7 +73,8 @@ def attributes
       if source
         source.attributes.
           reject { |a| IGNORED_ATTRIBUTES.include?(a) }.
-          merge(user: current_user)
+          merge(user: current_user).
+          merge(scientific_domain_ids: source.scientific_domain_ids)
```
Comment (jswk) [inline app/controllers/projects_controller.rb:77]: Why not just?
```
merge(user: current_user, scientific_domain_ids: source.scientific_domain_ids)
```

**Review by jswk — CHANGES_REQUESTED** [review]
Also, changelog

File: app/controllers/projects_controller.rb (hunk 1 above)
Comment (goreck888) [reply app/controllers/projects_controller.rb]: Done

**Review by kmarszalek — APPROVED** [review]

**Review by jswk — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]
