### PR TITLE
[#2103] Fix creating offers in ordering configuration

### LINKED ISSUE #2103: no possibility to add an offer by ordering configuration for the service with no offert status
3.12.0-beta.2
Tested 
**Describe the bug**
if the website does not have any offer, even the default one, it is not possible to add an offer by ordering configuration, the problem does not exist for backoffice

**To Reproduce**
1. Select resource for which you have admin privileges and delete all offers via API 
2. Go to resource page /services/{service.name}
3. Click button "Manage resource" and select "Set parameters and offers"
4. See error - user see information _You are not authorized to see this page_, but user has admin privileges and service is Published

**Expected behavior**
User should have possibility add offer

**Screenshots**
image

**Additional context**
View in Backoffice, user has possibility add new offert
image

### PR DESCRIPTION
**Pull request by goreck888**
Fix a possibility to create an offer in the ordering_configuration
panel when a resource has no offers
Fixes #2103

### CODE REVIEW

File: app/policies/ordering_configuration/offer_policy.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 # frozen_string_literal: true
 
-class OrderingConfiguration::OfferPolicy < ApplicationPolicy
+class OrderingConfiguration::OfferPolicy < OrderingConfigurationPolicy
```
Comment (jswk) [inline app/policies/ordering_configuration/offer_policy.rb:3]: Wouldn't you also want to override the `show?` method to return `offer_editor?`. `offer_editor?` captures a little broader category of users than just `record.administered_by?(user)` from `OrderingConfigurationPolicy`.
Also, for this class, `record.administered_by?` won't be a method, as it is only defined on Service, not on offer. This leads me to think changing the parent here isn't necessary at all, and will just create confusion.

File: app/views/services/ordering_configurations/_about.html.haml [hunk 2]
```diff
@@ -3,8 +3,7 @@
     %main.col-12.col-xl-9.pr-5.mb-4{ "data-shepherd-tour-target": "service-about" }
 
       = markdown(service.description)
-      - if policy(service).order? && !offers&.empty?
```
Comment (jswk) [inline app/views/services/ordering_configurations/_about.html.haml:6]: Why was the `policy(service).order?` applied here? Is it safe to remove it?

File: spec/features/ordering_configuration_spec.rb [hunk 3]
```diff
@@ -83,6 +83,34 @@
       expect(page).to_not have_link("Delete Offer")
     end
 
+    scenario "I can add an offer if no one exists", js: true do
```
Comment (jswk) [inline spec/features/ordering_configuration_spec.rb:86]: I'd phrase it "if none exists", to be correct

**Review by jswk — COMMENTED** [review]
I'm also thinking, there seems to be a discrepancy between `OrderingConfigurationPolicy` and `OrderingConfiguration::OfferPolicy`. In particular, the former is more restrictive than the latter. Do you know if it is a desired behaviour?

Also, changelog. ;)

File: app/policies/ordering_configuration/offer_policy.rb (hunk 1 above)
Comment (goreck888) [reply app/policies/ordering_configuration/offer_policy.rb:3]: Ok

File: spec/features/ordering_configuration_spec.rb (hunk 3 above)
Comment (goreck888) [reply spec/features/ordering_configuration_spec.rb:86]: Ok.

File: app/views/services/ordering_configurations/_about.html.haml (hunk 2 above)
Comment (goreck888) [reply app/views/services/ordering_configurations/_about.html.haml:6]: I think it's safe, moreover, it's necessary :)

Comment (jswk) [reply app/views/services/ordering_configurations/_about.html.haml:6]: Okay, what's the reason for this?

Comment (goreck888) [reply app/views/services/ordering_configurations/_about.html.haml:6]: As I suppose we assumed that default offer is indelible. Now we can remove all offers via offering API.

**Review by jswk — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]
