### PR TITLE
[#2255] Fix unauthorized access to ordering_configuration

### LINKED ISSUE #2255: Problems with authority to ordering_configuration page
Tested on beta v3.18.0-beta.0 and 3.17.x

**User without admin privilage role, not resource owner - service B2DROP** 

**beta v3.18.0-beta.0**
User can go to /ordering_congiguration page, when click on button "Add new offer" or "Edit" for existed offers see message"You are not authorized to see this page." and stay on /ordering_configuration page
image
image

**3.17.x**
User can't go to /ordering_configuration page, when try he/she is redirected to home page and see message ""You are not authorized to see this page""
image

**User with admin privilage role -  - service B2DROP.**

**beta v3.18.0-beta.0**
User can go to /ordering_configuration page, can edit, delete, create new offer

**3.17.x**
User can go to /ordering_configuration page, can edit, delete, create new offer

**User with PM role -  - service B2DROP.**
**beta v3.18.0-beta.0**
User can go to /ordering_configuration page, can edit, delete offer but **can't add new** 
image
image

**3.17.x**
User can't go to /ordering_configuration page, when try he/she is redirected to home page and see message ""You are not authorized to see this page""
image

**User lost admin privilage**
**beta v3.18.0-beta.0**
user lost the privilages but not refresh page from page https://beta.marketplace.eosc-portal.eu/services/b2drop can go to /services/b2drop/ordering_configuration#offers after click the button "Set parameters and offers". User can't add new offer, edit or delete. See message "You are not authorized to see this page", but stay on page /ordering_configuration
image

When user is on open page /services/b2drop/ordering_configuration/offers/new - and try click button "Create Offer" , see message This page isn’t working beta.marketplace.eosc-portal.eu redirected you too many times

When user is on open page /services/b2drop/ordering_configuration/offers/3/edit?from= - and try click button "Delete" or "Update Offer" see message This page isn’t workingbeta.marketplace.eosc-portal.eu redirected you too many times
image

after refresh page - user still on /ordering_configuration page

**3.17.x**
user lost the privilages but not refresh page from page https://beta.marketplace.eosc-portal.eu/services/b2drop can't go to /services/b2drop/ordering_configuration#offers after click the button "Set parameters and offers", see message "You are not authorized to see this page", page is rehresh and button "Manage resource" disapear
image

on page /ordering_configuration 
User after click the button "Add new" or "Edit" see message - . This page isn’t working localhost redirected you too many times.
image

When user is on open page /services/b2drop/ordering_configuration/offers/new and try click button "Create Offer" see message - This page isn’t working beta.marketplace.eosc-portal.eu redirected you too many times

When user is on open page /services/b2drop/ordering_configuration/offers/3/edit?from= and try click button "Delete" or "Update Offer" see message This page isn’t workingbeta.marketplace.eosc-portal.eu redirected you too many times
image

after refresh page - user is redirected to /services/b2drop#offers, message "You are not authorized to see this page"" is displayed.

### PR DESCRIPTION
**Pull request by goreck888**
Change the policy for Resource authorization
in `ordering_configurations_controller`
Pundit used default `ServiceContextPolicy`
instead of correct
`OrderingConfiguration::ServiceContextPolicy`
Fixes #2255

### CODE REVIEW

**Comment by Marcelinna** [comment]
only the resource administrator should be able to access / ordering_configuration, Portfolio Manager should not be able to access

File: app/policies/ordering_configuration/service_context_policy.rb [hunk 1]
```diff
@@ -2,6 +2,6 @@
 
 class OrderingConfiguration::ServiceContextPolicy < ServiceContextPolicy
   def show?
-    super && record.service.administered_by?(user)
+    super && (record.service.administered_by?(user) || user.service_portfolio_manager?)
```
Comment (jswk) [inline app/policies/ordering_configuration/service_context_policy.rb:5]: As @Marcelinna mentioned, this shouldn't be added.
The test will have to be adjusted.

File: app/controllers/services/ordering_configurations_controller.rb [hunk 2]
```diff
@@ -20,6 +20,7 @@ def show
   private
     def load_and_authenticate_service!
       @service = Service.friendly.find(params[:service_id])
-      authorize(ServiceContext.new(@service, params.key?(:from) && params[:from] == "backoffice_service"), :show?)
+      authorize(ServiceContext.new(@service, params.key?(:from) && params[:from] == "backoffice_service"), :show?,
+                policy_class: OrderingConfiguration::ServiceContextPolicy)
```
Comment (jswk) [inline app/controllers/services/ordering_configurations_controller.rb:24]: I don't like this construct, it seems to go against the rails conventions.

However, I've noticed a way this could be done better. Just make this class extend `Services::OrderingConfiguration::ApplicationController` instead of `Services::ApplicationController`, then the policy is resolved correctly.

Then you can safely drop the line 4 (i.e. `before_action :authenticate_user!`) from this class too.

**Review by jswk — CHANGES_REQUESTED** [review]

File: app/policies/ordering_configuration/service_context_policy.rb (hunk 1 above)
Comment (goreck888) [reply app/policies/ordering_configuration/service_context_policy.rb:5]: Ok

File: spec/features/ordering_configuration_spec.rb [hunk 3]
```diff
@@ -203,4 +203,32 @@
...
+      let(:provider) { create(:provider) }
+      let(:service) { create(:service, resource_organisation: provider, offers: [create(:offer)]) }
+
+      before { checkin_sign_in_as(user) }
+
+      scenario "I am#{authorized ? nil : " not"} authorized to see the ordering_configuration panel" do
+        visit service_ordering_configuration_path(service)
+
+        if authorized
+          visit service_ordering_configuration_path(service)
```
[the remark this answers is not in the document]
Comment (goreck888) [reply spec/features/ordering_configuration_spec.rb:220]: Done

**Review by jswk — APPROVED** [review]

**Comment by Marcelinna** [comment]
Steps to reproduce 
1. I am admin and go to resource
2. Resource has to offer, I choose one and click button "EDIT" 
3. I have two button (Delete offer and Update Offer)
image
4**. I lost admin privilage**
5. I click the button "Delete"
6. I see error 
image

@goreck888  Should I create a separate tiket for this issue?

**Review by Marcelinna — APPROVED** [review]
