### PR TITLE
Order change with service provider message

### LINKED ISSUE #199: Jira webhook integration does not support comments.
**Describe the bug**
Jira webhook integration does not support comments.

**To Reproduce**
  1. Order new service
  1. Find jira ticket connected with the service order
  1. Add new comment

**Expected behavior**
New comment is shown on the service order details list

**Current behavior**
```
11:29:27 web.1       | Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
11:29:27 web.1       | 
11:29:27 web.1       | 
11:29:27 web.1       |   
11:29:27 web.1       | NoMethodError (undefined method `[]' for nil:NilClass):
11:29:27 web.1       |   
11:29:27 web.1       | app/controllers/api/webhooks/jiras_controller.rb:27:in `create'
11:29:27 web.1       | Started POST "/api/webhooks/jira?user_id=admin&user_key=admin" for 127.0.0.1 at 2018-10-11 11:29:27 +0200
11:29:27 web.1       | Processing by Api::Webhooks::JirasController#create as */*
```

### PR DESCRIPTION
**Pull request by mkasztelnik**
When a new message is added in Jira it is also registered in MP as service provider message.

To make webhooks more generic (for the status update and messages) `issue_id` query param need to be defined. Otherwise, it was tricky to get issue id for new comment (url regexp was needed). This query param fixes problem (described in the `README.md`).

Fixes #199

### CODE REVIEW

File: app/controllers/api/webhooks/jiras_controller.rb [hunk 1]
```diff
@@ -1,52 +1,43 @@
...
 
 class Api::Webhooks::JirasController < ActionController::API
-  # before_action :find_and_authorize, only: [:show, :edit, :update, :destroy]
-
   class WebhookNotAuthorized < StandardError ; end
 
-  rescue_from(ActiveRecord::RecordNotFound) do
-    render json: { message: "No correlating order found" }
-  end
-
```
Comment (michal-szostak) [inline app/controllers/api/webhooks/jiras_controller.rb]: Why remove this handler?

Comment (mkasztelnik) [reply app/controllers/api/webhooks/jiras_controller.rb]: This was explained here https://github.com/cyfronet-fid/marketplace/pull/202/commits/f9f6f3220481a5e5a0e44c1569a0825f20bfe289.

**Comment by mkasztelnik** [comment]
@michal-szostak  you are right I forgot to add #199 reference -> PR description updated.
