### PR TITLE
[#1561] Improve welcome popup

### LINKED ISSUE #1561: Improve "new functionality arrived!" problem (cookies)
**To Reproduce**
1. Go to https://marketplace-beta.docker-fid.grid.cyf-kr.edu.pl/
2. Login
3. See attached screen (New functionality arrived)
4. Go to https://marketplace-beta.docker-fid.grid.cyf-kr.edu.pl/ using a private window
5. See attached screen one more time

**Expected behavior**
The attached screen should be visible only once

**Screenshots**

### PR DESCRIPTION
**Pull request by goreck888**
Showing welcome popup depends on user db variable now.
Changed from cookies variable
Fixes #1561

### CODE REVIEW

File: spec/features/home_spec.rb [hunk 1]
```diff
@@ -48,13 +48,31 @@
...
+        expect(page).to_not have_content ("New functionality arrived!")
+      end
     end
 
     context "user" do
       let(:admin) { create(:user) }
       before { checkin_sign_in_as(admin) }
 
-      it "should see error" do
+      it "shouldn't see error" do
```
Comment (martaswiatkowska) [inline spec/features/home_spec.rb:75]: More accurate is : "Should see warning messages"

Comment (martaswiatkowska) [inline spec/features/home_spec.rb:75]: maybe not error but "warning messages"?
