### PR TITLE
[#2066] Fix logic of adding offers to a project

### LINKED ISSUE #2066: wrong logic of adding offers to a project
tested on 3.11.0-beta.2
**Describe the bug**
the current logic does not allow adding two different offers of the same service to the same project if they do not have the properties (constant, input, select, multiselect, date, range, quantity price)

I order offer in existed services EGI Cloud Compute
1. Add **General purpose** (order required **with properties**) offer to **"project 1"** - it is ok
2. Add second time the same offer **General purpose** (order required **with properties**) offer to "**project 1"** - it is ok
3. Add other offert **Compute-intensive** (order required **with properties**) offer to **"project 1"** - it is ok
4. Add second time offert **Compute-intensive** (order required **with properties**) offer to **"project 1"** - it is ok

I order offer in existed services da|ra - DOI Registration Service for social science and economic data
1. Add **DOI Registration**  (order required **without properties**) offer to **"project 2"**- it is ok
2. Add second time **DOI Registration**  (order required **without properties**) offer to **"project 2"**- isn't ok, information is displayed _Please note that this resource can be added to the Project only once. Please choose another project_
3. Add other **Metadata harvesting** (open access **without properties**) offer to **project 2** - isn't ok _Please note that this resource can be added to the Project only once. Please choose another project_
4. Create **new offer with properties**, order required type and add to the **project 2** - it is ok

The same situation for default offert is the same, If default offer has properties can be added second time to the same project. if it doesn't have properties it can't be added second time. 
The question is whether properiets should decide about this, because it will be enough that it will be constant which makes almost no distinction between the offer with properties and without.

**Expected behavior**
We should decide how it should works. 

**EDIT**
The follow up development issue has been created #2393

@roksanaer @bwilk 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by kmarszalek**
open_access/fully_open_access/other offer can be added only once.
order_required - external can be added only once.
order_required - internal can be added multiple times.
bundled offer (parent and child) can be added multiple times.
child of the bundled offer can be added once if it is oa/foa/oo/or-e offer if it is ordered solo.

Closes #2066

### CODE REVIEW

**Comment by jswk** [comment]
> **Fix** logic of adding offers to a project

How about simplify? It's actually about clearing up the logic there.

**Comment by Marcelinna** [comment]
I can add many time the same offer open access 
image

File: spec/factories/services.rb [hunk 1]
```diff
@@ -10,9 +10,15 @@
     factory :open_access_service do
       sequence(:order_type) { :open_access }
     end
-    factory :fully_open_access_servoce do
+    factory :fully_open_access_service do
       sequence(:order_type) { :fully_open_access }
     end
+    factory :other do
```
Comment (jswk) [inline spec/factories/services.rb:16]: => `other_service`

File: spec/factories/services.rb [hunk 2]
```diff
@@ -10,9 +10,15 @@
...
+      sequence(:order_type) { :other }
+    end
+    factory :order_required do
```
Comment (jswk) [inline spec/factories/services.rb:19]: => `order_required_service`

**Review by jswk — CHANGES_REQUESTED** [review]

**Review by jswk — APPROVED** [review]

**Comment by Marcelinna** [comment]
Steps to reproduce:
1. Go to /services
2. Choose B2FIND
image
3. Order the first offer
4. Order the second offer - "Project already pinned with this offer" error message is displayed

Expected result: second offer should be ordered properly

**Comment by Marcelinna** [comment]
Tests: 

1. Add offer open access
2. Add offer full open access
3. Add offer other
4. Add order required internal
5. Add order required external
6. Try to add second time the same offer open acccess 
7. Try to add second time the same offer full open acccess 
8. Add second time the same offer order required internal
9. Try to add second time the same offer order required external
10. Try to add second time the same offer other
11. Try add offer open access and order required internal from the same service
12. Try add offer order required and open access from the same service
13. Try add two open access offer from the same services
14. Try add two order required internal offer from the same services

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Add to project service open access
2. Try add the same service open access to the same project
3. See error - user is redirected to previous step
image

**Review by jswk — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]
