### PR TITLE
[#2047] Move "Other" target user at the end of a list

### LINKED ISSUE #2047: Target Users list has duplicates
**Describe the bug**
there are duplicates in the target user list (Business, Bussinesses, Research Groups, Research groups, Research organisation, Research Organisations)

Please put **Other** at the end of the list

**To Reproduce**
1. Go to 'https://marketplace.eosc-portal.eu/target_users'
2. See error

image

Link to documentation https://confluence.egi.eu/pages/viewpage.action?pageId=64914897

### PR DESCRIPTION
**Pull request by goreck888**
As a part of ticket #2047 there was a need to move
"Other" target user at the end of list
available at `/target_users/` page
Fixes #2047

### CODE REVIEW

**Review by Marcelinna — APPROVED** [review]

File: app/controllers/pages_controller.rb [hunk 1]
```diff
@@ -8,10 +8,10 @@ def about_projects
   end
 
   def communities
-    @platforms = Platform.all.order(:name)
+    @platforms = Platform.all.order(:name).partition { |p|  p.name != "Other" }.flatten(1)
```
Comment (jswk) [inline app/controllers/pages_controller.rb:11]: Why modify the order for the communities/platforms too? I don't see an "Other" entry there: https://marketplace.eosc-portal.eu/communities

Comment (goreck888) [reply app/controllers/pages_controller.rb]: Ok, removed

**Review by jswk — APPROVED** [review]
