### PR TITLE
[#2472] Fix clearing a resource form

### LINKED ISSUE #2472: The form is cleared after clicking the "Create resource" button, if user previously clicked "Preview" on an empty form
Tested:
3.28.0-beta.0

**Describe the bug**
The form is cleared after clicking the "Create resource" button, if you previously clicked "Preview" on an empty form

**To Reproduce**
1. Go to '/backoffice/services'
2. Click on the 'Preview' button
3. Fill required field in the form
4. Click on the 'Create resource' button
5. See error - resource isn't create, whole form is cleared
image

**Expected behavior**
Resource is created

### PR DESCRIPTION
**Pull request by goreck888**
Click on a `Preview` button when the form is empty
caused saving empty attributes in a session.
Then after filling the form and click on
"Create Resource" the priority was in session attributes
Fixes #2472

### CODE REVIEW

File: app/controllers/backoffice/services_controller.rb [hunk 1]
```diff
@@ -150,7 +151,7 @@ def perform_create
     if @service.persisted?
       update_logo_from_session!
       session.delete(preview_session_key)
-      redirect_to backoffice_service_path(@service), notice: "New service created successfully"
+      redirect_to backoffice_service_path(@service), notice: "New resource created successfully"
     else
       add_missing_nested_models
```
Comment (Marcelinna) [inline app/controllers/backoffice/services_controller.rb:156]: You need make change in e2e test

Comment (jswk) [reply app/controllers/backoffice/services_controller.rb:156]: Shouldn't this service=>resource thingy be addressed in #2475 anyway?

I would just revert the change in this line

**Review by jswk — COMMENTED** [review]
Apart from my suggestion to revert the naming change this PR is fine.

**Review by Marcelinna — APPROVED** [review]

File: app/controllers/backoffice/services_controller.rb (hunk 1 above)
Comment (goreck888) [reply app/controllers/backoffice/services_controller.rb:156]: Ok I'll revert it, but I want to merge #2475 first.

**Review by jswk — APPROVED** [review]

**Review by kmarszalek — APPROVED** [review]
