### PR TITLE
[#2014] Obfuscate user_direct message content

### LINKED ISSUE #2014: Add user_direct message content obfuscation to Ordering API
We need to make sure that when messages are returned to OMS admins via our Ordering API, and when their scope is `user_direct`, the content is obfuscated (the only exception is when returning a message JSON object from `POST /api/v1/{oms_id}/messages` and `PATCH /api/v1/{oms_id}/messages/{m_id}`). 

When editing a content of `user_direct` message an `update` event is created and `changes` object is added to this event. The `changes` here needs to look like (only when serialized):
```
{
  "field": "content",
  "before": "<OBFUSCATED>",
  "after": "<OBFUSCATED>",
}
```

### PR DESCRIPTION
**Pull request by wujuu**
Closes #2014 

How to test @Marcelinna (mostly copied from https://github.com/cyfronet-fid/marketplace/pull/1982#issuecomment-823921757):

We will artificially create a following situation:
- SOMBO (default), OMS2 and OMS3 omses and their admins
- Project1 (p1) which doesn't have any project_items, but has 2 messages (message1_1 (author: user, scope: public), message1_2 (author: mediator, scope: public))
- Project2 (p2) which has 1 project_item (project_item2_1 (assigned to OMS2)) and no messages
- Project3 (p3) which has 2 project_items (project_item3_1 (assigned to OMS2), project_item3_2 (assigned to OMS3)) and 2 messages (**message3_1 (author: provider, scope: public), message3_2 (author: provider, scope: user_direct)**)

Run
```
rails db:drop db:create db:migrate
rails dev:prime # includes add_sombo task
rails ordering_api:authorization_test_setup
```

Then run this to get admin tokens:
```
rails c
> User.find_by(uid: "iamasomboadmin").authentication_token
> User.find_by(uid: "oms2_admin").authentication_token
> User.find_by(uid: "oms3_admin").authentication_token
```
Copy tokens and use them as 'X-User-Token' in `/api_docs/swagger` (select Ordering API from the top right drop down menu)

Then:
```
POST /api/v1/oms/2/messages
X-User-Token: OMS2 user token
{
  "project_id": 3,
  "project_item_id": 1,
  "content": "super duper secret conrent for user's eyes only",
  "author": {
    "email": "email@email.com",
    "name": "some name",
    "role": "provider"
  },
  "scope": "user_direct"
}
```
(lets call this message **message3_1_1**)

```
POST /api/v1/oms/3/messages
X-User-Token: OMS3 user token
{
  "project_id": 3,
  "project_item_id": 2,
  "content": "public message for every1 to see",
  "author": {
    "email": "email@email.com",
    "name": "some name",
    "role": "provider"
  },
  "scope": "public"
}
```
(lets call this message **message3_2_1**)

```
POST /api/v1/oms/1/messages
X-User-Token: SOMBO user token
{
  "project_id": 3,
  "project_item_id": 2,
  "content": "internal message from mediator",
  "author": {
    "email": "email@email.com",
    "name": "some name",
    "role": "mediator"
  },
  "scope": "internal"
}
```
(lets call this message **message3_2_2**)

Request should result in 200 success and return created items **along with full un-obfuscated contents** - note the message ids!

Then:

8. GET /api/v1/oms/{oms_id}/messages
- `oms_id` = SOMBO id
  - `p_id` = p3 id (query param)
  - as SOMBO admin I should see ['message3_1', 'message3_2'] and status 200 **BUT the message3_2 should have obfuscated content**
    - `pi_id` = project_item3_1 id (query param)
      - as SOMBO admin I should see ['message3_1_1''] and status 200 **BUT the message3_1_1 should have obfuscated content**
    - `pi_id` = project_item3_2 id (query param)
      - as SOMBO admin I should see ['message3_2_1, message3_2_2''] and status 200
- `oms_id` = OMS2 id
  - `p_id` = p3 id (query param)
  - as OMS2 admin I should see ['message3_1', 'message3_2'] and status 200 **BUT the message3_2 should have obfuscated content**
     - `pi_id` = project_item3_1 id (query param)
       - as OMS2 admin I should see ['message3_1_1''] and status 200 **BUT the message3_1_1 should have obfuscated content**
    - `pi_id` = project_item3_2 id (query param)
      - as OMS2 admin I should see 404 "error": "Project item not found"
- `oms_id` = OMS3 id
  - `p_id` = p3 id (query param)
  - as OMS2 admin I should see ['message3_1', 'message3_2'] and status 200 **BUT the message3_2 should have obfuscated content**
     - `pi_id` = project_item3_1 id (query param)
       - as OMS3 admin I should see 404 "error": "Project item not found"
    - `pi_id` = project_item3_2 id (query param)
      - as OMS3 admin I should see ['message3_2_1, message3_2_2''] and status 200

10. GET /api/v1/oms/{oms_id}/messages/{m_id}
   Every OMS should be able to see messages specified in "GET /api/v1/oms/{oms_id}/messages" - any other combination of oms_id and m_id should result in either 403 unauthorized or 404 project/messsage not found **BUT the message3_1_1 AND message3_2 should have obfuscated content**

11. PATCH /api/v1/oms/{oms_id}/messages/{m_id}
- `oms_id` = SOMBO id
  - `m_id` = message3_1_1
    - as a SOMBO admin I should not be able to edit message, and get 403 unauthorized
  - `m_id` = message3_2_1
    - as a SOMBO admin I should not be able to edit message, and get 403 unauthorized
  - `m_id` = message3_2_2
    - as a SOMBO admin I should be able to edit "content" of the message **and returned message should have full un-obfuscated content**
- `oms_id` = OMS2 id
  - `m_id` = message3_1_1
    - as a OMS2 admin I should be able to edit "content" of the message **and returned message should have full un-obfuscated content**
  - `m_id` = message3_2_1
    - as a OMS2 admin I should get 404 message not found
  - `m_id` = message3_2_2
    - as a OMS2 admin  I should get 404 message not found
- `oms_id` = OMS3 id
  - `m_id` = message3_1_1
    - as a OMS3 admin I should get 404 message not found
  - `m_id` = message3_2_1
    - as a OMS3 admin I should be able to edit "content" of the message **and returned message should have full un-obfuscated content**
  - `m_id` = message3_2_2
    - as a OMS3 admin I should not be able to edit message, and get 403 unauthorized
   
12. GET /api/v1/oms/{oms_id}/events
- `oms_id` = SOMBO id
  - as a SOMBO admin I should see events connected to: p1, p2, p3, project_item2_1, project_item3_1, project_item3_2, message1_1, message1_2, message3_1, message3_2, message3_1_1, message3_2_1, message3_2_2 **(but IF you updated the "content" of either message3_2 or message3_1_1 the event['changes] should have obfuscated content!)**
- `oms_id` = OMS2 id
  - as a OMS2 admin I should see events connected to: p2, p3, project_item2_1, project_item3_1, message3_1, message3_2, message3_1_1 **(but IF you updated the "content" of either message3_2 or message3_1_1 the event['changes] should have obfuscated content!)**
- `oms_id` = OMS3 id
  - as a OMS3 admin I should see events connected to: p3, project_item3_2, message3_1, message3_2, message3_2_1, message3_2_2 **(but IF you updated the "content" of message3_2 the event['changes] should have obfuscated content!)**

### CODE REVIEW

File: app/serializers/ordering_api/v1/event_serializer.rb [hunk 1]
```diff
@@ -36,4 +37,10 @@ def changes
       object.eventable.eventable_identity[identity_part]
     end
   end
+
+  private
+    def should_obfuscate?(field)
+      field == "user_secrets" ||
+        (field == "message" && object.eventable_type == "Message" && object.eventable.user_direct_scope?)
```
Comment (jswk) [inline app/serializers/ordering_api/v1/event_serializer.rb:44]: Maybe even better?
```ruby
case object.eventable_type
when "Message":
  field == "message" && object.eventable.user_direct_scope?
when "ProjectItem":
  field == "user_secrets"
```

File: app/serializers/ordering_api/v1/event_serializer.rb [hunk 2]
```diff
@@ -23,10 +23,11 @@ def resource
 
   def changes
     object.updates&.map do |update|
-      if update["field"] == "user_secrets"
+      if should_obfuscate?(update["field"])
         update["after"] = "<OBFUSCATED>"
         update["before"] = "<OBFUSCATED>"
       end
+      update["field"] = "content" if update["field"] == "message"
```
Comment (jswk) [inline app/serializers/ordering_api/v1/event_serializer.rb:30]: I'd extract it to a method too, there will be the ProjectItem fields which need to be mapped (for example `status` => `status.value`).

Comment (jswk) [reply app/serializers/ordering_api/v1/event_serializer.rb:30]: And it could be a readable `case` as for the `should_obfuscate?`.

**Review by jswk — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
3_2_3 message content isnt obfuscated. Mistake in documentation ?

**Comment by Marcelinna** [comment]
PATCH /api/v1/oms/{oms_id}/messages/{m_id}
image
3_2_1 message content isnt obfuscated. Mistake in documentation ?

**Comment by Marcelinna** [comment]
We shouldn't test PATCH /api/v1/oms/{oms_id}/messages/{m_id} for message 3_1 and 3_2 ?

**Comment by Marcelinna** [comment]
who has possivle update message id = 4? I have no authorization every time (sombo, oms2, oms3)
Why oms2 cant update message id=5 but cant message id=4?

**Comment by wujuu** [comment]
> who has possible update message id = 4? (3_2) I have no authorization every time (sombo, oms2, oms3)
> 
> You wrote, but I cant update 3_2 message
> image

Actually, no one can edit this message (3_2), as it is a provider message user_direct message belonging to a project. My bad - but it is as expected:
image
 
To test the project message obfuscation (as opposed to project_item message obfuscation which you have already tested) do this:

Rerun the setup again:
```
rails db:drop db:create db:migrate
rails dev:prime # includes add_sombo task
rails ordering_api:authorization_test_setup
```

Then run this to get admin tokens:
```
rails c
> User.find_by(uid: "iamasomboadmin").authentication_token
> User.find_by(uid: "oms2_admin").authentication_token
> User.find_by(uid: "oms3_admin").authentication_token
```
Copy tokens and use them as 'X-User-Token' in `/api_docs/swagger` (select Ordering API from the top right drop down menu)

Then:

```
POST /api/v1/oms/1/messages
X-User-Token: SOMBO user token
{
  "project_id": 2,
  "content": "super duper secret conrent for user's eyes only FROM mediator(SOMBO)",
  "author": {
    "email": "email@email.com",
    "name": "some name",
    "role": "mediator"
  },
  "scope": "user_direct"
}
```
(lets call this message *message 2_1**
Request should result in 200 success and return created message **along with full un-obfuscated contents** - note the message id!

```
PATCH /api/v1/oms/1/messages/{message 2_1}
{ "content": "asdsadsadasd" }
```

Request should result in 200 success and return created message **along with full un-obfuscated contents**.

GET /api/v1/oms/1/events:
 - as a SOMBO admin I should see events connected to: p1, p2, p3, project_item2_1, project_item3_1, project_item3_2, message1_1, message1_2, message3_1, message3_2, **message2_1 (event["changes"] should be obfuscated)**

**Review by Marcelinna — APPROVED** [review]
