### PR TITLE
Elasticsearch index changes

### LINKED ISSUE #856: Elasticsearch index and highlights for service tagline
**Describe the bug**
Instead of tagline we use descrtiption for search 

**To Reproduce**
In `app/views/services/_service.html.haml` we use `%p.mb-3= service.tagline` - check it yourself. This field should be indexed and used for elasticsearch queries. 

**Expected behavior**
Tagline should be used instead. Selected services should have highlights for tagline.

### PR DESCRIPTION
**Pull request by martaswiatkowska**
Added tagline to elasticsearch index
Setted different weights for elasticsearch fields
Added highlights for tagline
Changed autocomplete routing and fixed autocomplete function

Fix #856

### CODE REVIEW

File: app/helpers/service_helper.rb [hunk 1]
```diff
@@ -47,4 +47,8 @@ def providers_text(service)
   def service_title(service, highlights)
     highlights&.dig(service.id, :title)&.html_safe || service.title
   end
+
+  def service_tagline(service, highlights)
```
Comment (mkasztelnik) [inline app/helpers/service_helper.rb]: This method is similar like `service_title`, you can extract it into separate method and reuse code.
