### PR TITLE
[#1952] Fix validation of min max values in multiselect

### LINKED ISSUE #1952: Setting min and max values ​​for multiselect (offert parameters)
Tested on 3.10.0-beta.0
**Describe the bug**
if when creating offerty parameters user enters wrong values ​​for min and max, it is not possible to order an offert later

**To Reproduce**
1. Go to backoffice in Marketplace (/backoffice/services)
2. Select a service 
3. Click button <_Set parameters and offers>
4. Click the button <_Edit parameters>
image
5. Click on 'Multiselect' and enter value

- When user set for **min** and **max** 0,0. It isnt posiible order the service

image
image
image
image
image
image

- When user set for **min** and **max** 0,1. It isnt posiible order the service without selecting. **Probably the setting for min 0 should be not allowed**
image
image

- it is possible enter negative number (works like 0)
image

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by goreck888**
- Change minimum value of selected
items to default 1 instead of 0
- Add validation for min < max

Fixes #1952

### CODE REVIEW

File: app/models/parameter/multiselect.rb [hunk 1]
```diff
@@ -6,14 +6,14 @@ class Parameter::Multiselect < Parameter
 
   attribute :unit, :string
 
-  validates :min, numericality: { less_than_or_equal_to: ->(p) { p.values&.length || 0 } }
-  validates :max, numericality: { less_than_or_equal_to: ->(p) { p.values&.length || 0 } }
+  validates :min, numericality: { less_than: :max, less_than_or_equal_to: ->(p) { p.values&.length || 1 } }
+  validates :max, numericality: { greater_than: :min, less_than_or_equal_to: ->(p) { p.values&.length || 0 } }
```
Comment (kmarszalek) [inline app/models/parameter/multiselect.rb:10]: nope.

**Review by kmarszalek — CHANGES_REQUESTED** [review]
- tests
- fix validation for max

File: app/models/parameter/multiselect.rb (hunk 1 above)
Comment (kmarszalek) [reply app/models/parameter/multiselect.rb:10]: Zrzut ekranu 2021-04-22 o 08 27 07

**Comment by kmarszalek** [comment]
Zrzut ekranu 2021-05-13 o 08 18 45

**Review by kmarszalek — APPROVED** [review]
