### PR TITLE
[#919] Stay in project modal when project empty while ordering

### LINKED ISSUE #919: Clicking twice "Create' button during creating a new project causes incorrect redirection
**Describe the bug**
When we click twice on the "Create" button during creating a new project from service ordering form we are redirecting from the view and we lost information about the service

**To Reproduce**
1. Go to any service eg. Cloud Ferro 
2. Click on 'Add to a project'
3. Click "Add new project"
4. See the empty form

5. Click "Create" while the form is empty or form doesn't have filled all relevant fields 
 
6. Click "Create" one more time and see
 error

**Expected behavior**
Clicking the "Create" button should always leave a user on the current form

**Additional context**
You can check this bug on Sprint PR: https://marketplace-14.docker-fid.grid.cyf-kr.edu.pl/

### PR DESCRIPTION
**Pull request by bwilk**
Redirection to project edit view on project creation failure while ordering is fixed. User stays in this modal after fix:

Zrzut ekranu 2019-06-24 o 12 14 47

Fixes #919

### CODE REVIEW

File: spec/features/order_spec.rb [hunk 1]
```diff
@@ -261,6 +261,26 @@
...
+
+      click_on "Order"
+      click_on "Add new project"
+
+      click_on "Create new project"
+      within("#ajax-modal") do
+        expect(page).to have_button("Create new project")
+      end
+
+      click_on "Create new project"
```
Comment (mkasztelnik) [inline spec/features/order_spec.rb]: Why do you need to validate this action twice?

File: app/controllers/projects_controller.rb [hunk 2]
```diff
@@ -62,6 +62,7 @@ def create
           Project::Create.new(@project).call
           render :show
         else
+          @show_as_modal = true
```
Comment (mkasztelnik) [inline app/controllers/projects_controller.rb]: Maybe this is a good time to get rid of this flag?

File: spec/features/order_spec.rb (hunk 1 above)
Comment (bwilk) [reply spec/features/order_spec.rb]: TDD approach here - because this is the method to reproduce the bug I'm fixing. First you try to save empty, then you try again - this is when the old implementation first.

File: app/controllers/projects_controller.rb (hunk 2 above)
Comment (bwilk) [reply app/controllers/projects_controller.rb]: I've reduced the use of it to minimum.
