### PR TITLE
services column width and affiliations bg color

### LINKED ISSUE #382: Strange color of affiliations in profile view
There were some styles added, which messed up the colors in the affiiation list. (The background color of affiliations is wrong.)

### LINKED ISSUE #408: Problem with buttons when page size is small
**Describe the bug**
Wrong service buttons scalling

**To Reproduce**
1. Got to one of the open access service (e.g. `GEOSS DAB`)
1. make browser smaller

**Expected behavior**
Nice looking service buttons :smile: 

**Screenshots**
buttons-problem

**Additional context**

### LINKED ISSUE #472: Browse all services button - empty link
On home page we have button Browse all services below slider. Link it to all services. Same link as All categories on sidebar.

### LINKED ISSUE #473: Background for home page
Add background to home page.
Preview https://invis.io/GKP0QKCDHQE#/329935671_Start
bg-lines

### PR DESCRIPTION
**Pull request by jarekzet**
Fixes #408 
Fixes #382
Fixes #472
Fixes #473

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -218,18 +218,18 @@
...
-    t.string "terms_of_use_url"
-    t.string "access_policies_url"
-    t.string "corporate_sla_url"
-    t.string "webpage_url"
-    t.string "manual_url"
-    t.string "helpdesk_url"
-    t.string "tutorial_url"
-    t.string "restrictions"
-    t.string "phase"
+    t.text "places", null: false
```
Comment (mkasztelnik) [inline db/schema.rb]: @jarekzet how this is connected with this PR? Please remove it from your last commit.

**Comment by mkasztelnik** [comment]
I already updated PR description to autoclose related issued when this PR is merged.

**Comment by mkasztelnik** [comment]
@jarekzet this is so terribly wrong. You cannot delete `db/schema.rb`! Just remove changes in `db/schemar.rb` you made.
