### PR TITLE
[#2209] Recommendations disappearing for certain view options

### LINKED ISSUE #2209: Recommendations disappearing for certain view options
**Describe the bug**
Recommendations panel disappears after change of number of displayed items from 10 to 20 (for both logged and anonymous user).

**To Reproduce**

Scenario 1:

    1. Visit `/services`
    2. Click button `20` to change number of displayed items.
Scenario 2:

    1. Visit `/services`
    2. Click page change button on the pagination section.

**Expected behavior**
Recommendations panel remains in above scenarios.

**Screenshots**
Scenario 1:
image

Scenario 2:
image

### PR DESCRIPTION
**Pull request by wujuu**
Closes #2209

### CODE REVIEW

File: app/controllers/concerns/service/recommendable.rb [hunk 1]
```diff
@@ -88,7 +101,7 @@ def get_filters_by(params)
       filters = {}
       unless params.nil?
         params.each do |key, value|
-          next if key == "controller" || key == "action" || value.blank?
+          next unless ALLOWED_SEARCH_DATA_FIELDS.include? key.to_sym
```
Comment (JanKapala) [inline app/controllers/concerns/service/recommendable.rb]: No value.blank?

**Review by JanKapala — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]
