### PR TITLE
[#783] Service counters fix. Filters and categories moved to elasticsearch 

### LINKED ISSUE #783: As a user when searching for service I want to see item count related to number of search results.
#### 1. Query entered by the user in the search bar

This is the main querying mechanism and all other levels need to receive result scope of this query

#### 2. Categories

Category item shows a number of services in a category and all subcategories limited by query scope (from point 1). When a category is selected query scope need to limit services only to services from the selected category.

#### 3. Filters

> :warning: This is the most complicated element :warning: 

For every filter, we need to calculate how many services are in each filter element without this filter applied. So for each filter, we need to take scope from point 2, add constants from other filters and do aggregation for the selected filter.

**Optimization** not selected filters can be grouped together and joined aggregation query can be applied once. 

#### 4. Shown services

The scope from point 2 should be taken and all selected filters should be applied.

#### 1 elasticsearch query - no filters selected

This is possible only when filters are not selected, category and query string can be present. In this situation, one elasticsearch query with aggregation for categories and all filters can be sent. 

#### 2-N+1 elasticsearch queries - 1 or more filters selected

 - First elasticsearch query is done to calculate categories count
 - The second elasticsearch query is done to calculate filters count for all unselected filters
 - N elasticsearch queries (where N is a number of selected filters) is done to calculate selected filter items counts.
  - N+1 elasticsearch query is done with all filters values is sent to show services list 

### Caching possibilities

Caching can speed up service browsing a lot, especially, when the user is navigating through the searched services (paging).  Caching can be done on different levels (category counts, filter counts).

@roksanaer, @bwilk, @abacz, @agpul, @kmarszalek, @martaswiatkowska, @michal-szostak comment if something in this description is wrong, not clear. I will try to improve this description and finally update this issue description.

### Filter items sorting and visibility

  1. Items are sorted using `count` value. If the filter is tree based subtrees are sorted in a similar manner.
  1. No items are removed from the list, what is more, a user should be able to select item even when currently count is equal to 0. The reason for this behavior is that this count could be changed on other filters changes.

### Filter cleaning

Filters are cleaned only when search query changes.

### PR DESCRIPTION
**Pull request by bwilk**
Fixes #783 
Description in the ticket itself

Changed:
- Reimplemented filters and categories after creating indexes in Elasticsearch 

Fixed:
- Category and filter counters 
- Hierarchical filters deactivation buttons
- Choice of "best match" sorting strategy after search 

Moved redirect after selecting a service in the search field after autocompletion: https://github.com/cyfronet-fid/marketplace/pull/916

### CODE REVIEW

File: app/models/filter/location.rb [hunk 1]
```diff
@@ -1,10 +1,12 @@
 # frozen_string_literal: true
 
 class Filter::Location < Filter
+  #   TODO finish this filter
```
Comment (kmarszalek) [inline app/models/filter/location.rb]: TODO?

Comment (bwilk) [reply app/models/filter/location.rb]: yep :)

File: app/controllers/concerns/service/searchable.rb [hunk 2]
```diff
@@ -6,10 +6,57 @@ module Service::Searchable
...
     include Paginable
     include Service::Sortable
+    include Service::Categorable
   end
 
-  def search(search_scope)
-    query_present? ? search_fields(search_scope) : paginate(order(search_scope.distinct))
+  def search(search_scope, filters)
+    Service.search(query,
+                   fields: [ "title^7", "tagline^3", "description"],
```
Comment (michal-szostak) [inline app/controllers/concerns/service/searchable.rb]: I think we could try to extract constant & common part of the `Service.search` call:

```
{
fields: [ "title^7", "tagline^3", "description"],
operator: "or",
match: :word_middle,
}
```

This would have an added benefit of extraction of "magic constants" (`"title^7"` etc)

Comment (bwilk) [reply app/controllers/concerns/service/searchable.rb]: Done
