### PR TITLE
feat:[#3595] Fix DS plain text pass

### LINKED ISSUE #3595: Fix plan text pass in the UI
Image

(add a standard "*****" with a "show password" button)

### PR DESCRIPTION
**Pull request by wujuu**
Closes #3595

### CODE REVIEW

File: app/javascript/controllers/sensitive_field_controller.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+export default class extends Controller {
+  static targets = ["display", "icon"];
+  static values = { revealed: { type: Boolean, default: false } };
+
+  toggle() {
+    this.revealedValue = !this.revealedValue;
+  }
+
+  revealedValueChanged() {
+    const realValue = this.element.dataset.sensitiveFieldRealValue;
```
Comment (Michal-Kolomanski) [inline app/javascript/controllers/sensitive_field_controller.js]: lets read that only once 
`this.realValue = this.element.dataset.sensitiveFieldRealValue || "";`
